### ISSUE TITLE
How it works with docker for development

### ISSUE THREAD

**Issue by amerej** [vitorsalgado/create-nodejs-ts#276]
Hi, thank you for your project, i have question how it's supposed to work in development?
I try this command:
`docker-compose -f deployments/dev/docker-compose.yml up`
But there is no npm install in Dockerfile.dev so there is no nodemon and npm start fail.
Did i missing something ?

**Comment by vitorsalgado** [comment]
Hello @amerej, the deployments/dev/docker-compose.yml configures a volume pointing to the project root folder and it expects everything to be installed locally before running the container. So you need to run npm install first, for now.  
I think this is something that could be improved 🤔

**Comment by vitorsalgado** [comment]
Just published an improved version of the docker-compose.yml.  
https://github.com/vitorsalgado/create-nodejs-ts/blob/main/deployments/dev/docker-compose.yml

**Comment by amerej** [comment]
Hi, sorry for my late response, thank you for the improvement it works like a charm.
